CREATE TABLE Learners (
  LearnerId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  FullName NVARCHAR(200) NOT NULL,
  RoleSelected NVARCHAR(120) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Courses (
  CourseId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  CourseCode NVARCHAR(50) NOT NULL UNIQUE,
  CourseName NVARCHAR(200) NOT NULL,
  VersionLabel NVARCHAR(50) NOT NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Enrollments (
  EnrollmentId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  LearnerId UNIQUEIDENTIFIER NOT NULL,
  CourseId UNIQUEIDENTIFIER NOT NULL,
  StartDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  LastActivity DATETIME2 NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'in_progress',
  LastStepId NVARCHAR(80) NULL,
  CycleYear INT NOT NULL,
  CONSTRAINT FK_Enrollments_Learners FOREIGN KEY (LearnerId) REFERENCES Learners(LearnerId),
  CONSTRAINT FK_Enrollments_Courses FOREIGN KEY (CourseId) REFERENCES Courses(CourseId),
  CONSTRAINT UQ_Enrollment UNIQUE (LearnerId, CourseId, CycleYear)
);

CREATE TABLE Certificates (
  CertificateId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  EnrollmentId UNIQUEIDENTIFIER NOT NULL,
  IssuedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CompletionDate DATETIME2 NOT NULL,
  CertificateCode NVARCHAR(50) NOT NULL,
  PdfUrl NVARCHAR(500) NULL,
  CONSTRAINT FK_Certificates_Enrollments FOREIGN KEY (EnrollmentId) REFERENCES Enrollments(EnrollmentId),
  CONSTRAINT UQ_CertCode UNIQUE (CertificateCode)
);

CREATE TABLE EnrollmentEvents (
  EventId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  EnrollmentId UNIQUEIDENTIFIER NOT NULL,
  EventType NVARCHAR(50) NOT NULL,
  EventAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  Metadata NVARCHAR(MAX) NULL,
  CONSTRAINT FK_Events_Enrollments FOREIGN KEY (EnrollmentId) REFERENCES Enrollments(EnrollmentId)
);
